version: '3.2'
services:
  php-fpm:
    build: ./php/
    ports:
      - "9002:9000"
    links:
      - mysql-db:mysql-db
      - redis-db:redis-db
    volumes:
      - ../app:/data/www:rw
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro # 当前php配置文件；可以拷贝修改php-dev.ini为想要的配置
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ../logs/php-fpm:/var/log/php-fpm:rw
    restart: always
    command: php-fpm
  nginx:
    build: ./nginx
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - ../app:/data/www:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs/:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
      - "8400:8400"
      - "8402:8402"
      - "8404:8404"
      - "8406:8406"
      - "8408:8408"
      - "8410:8410"
      - "8412:8412"
      - "8414:8414"
      - "8416:8416"
      - "8418:8418"
      - "8420:8420"
      - "8422:8422"
      - "8424:8424"
      - "8426:8426"
      - "8428:8428"
      - "8430:8430"
      - "8432:8432"
      - "8434:8434"
      - "8436:8436"
      - "8438:8438"
      - "8440:8440"
      - "8442:8442"
      - "8444:8444"
      - "8446:8446"
      - "8448:8448"
      - "8501:8501"
      - "8503:8503"
      - "8505:8505"
      - "8507:8507"
      - "8509:8509"
      - "8511:8511"
      - "8513:8513"
      - "8515:8515"
      - "8517:8517"
      - "8519:8519"
      - "8521:8521"
      - "8523:8523"
      - "8525:8525"
      - "8527:8527"
      - "8529:8529"
      - "8531:8531"
      - "8533:8533"
      - "8535:8535"
      - "8537:8537"
      - "8539:8539"
      - "8541:8541"
      - "8543:8543"
      - "8545:8545"
      - "8547:8547"
      - "8549:8549"
    restart: always
    command: nginx -g 'daemon off;'
  mysql-db:
      build: ./mysql
      ports:
        - "3308:3306"
      volumes:
        - ../data/mysql:/var/lib/mysql:rw
        - ../logs/mysql:/var/lib/mysql-logs:rw
        - ./mysql/conf.d:/etc/mysql/conf.d:ro
      environment:
        MYSQL_ROOT_PASSWORD: vegeta1617
        MYSQL_DATABASE: dboadmin
        MYSQL_USER: dbouser
        MYSQL_PASSWORD: dbo3308
      restart: always
      command: "--character-set-server=utf8"

  redis-db:
      build: ./redis
      ports:
        - "6381:6379"
      volumes:
        - ../data/redis:/data
      restart: always